name:C++ CI Pipeline

on:[push]

jobs:
build:
runs-on: ubuntu-lastest

steps:
-uses: action/checkout@v3

-name: install builds tools
run: | 
sudo apt update
sudo apt install -y cmake g++
name: Configure project
run: |
cmake-S. -B build

-name: Build project
run: | 
cmake--build build 
-name: Run tests
run: |
cd build
ctest--output--on--failure
